<?php
/**
 * Contact
 *
 * @author Slava Yurthev
 */
?>
<?php $fields = $block->getFields(); ?>
<?php if (count($fields) > 0): ?>
    <form class="form contact" action="<?= $block->getUrl('customcontact/form/post'); ?>" id="contact-form"
          method="post" data-mage-init='<?= $block->getJsFormConfig() ?>'>
        <input type="hidden" name="form_key" value="<?= $block->getFormKey(); ?>">
        <fieldset class="fieldset">
            <legend class="legend"><span><?= __('Write Us'); ?></span></legend>
            <div class="field note no-label">
                <?= __('Jot us a note and we’ll get back to you as quickly as possible.'); ?>
            </div>
            <?php foreach ($fields as $field): ?>
                <div class="field <?= $field->getData('key'); ?> <?= $field->getData('field_class'); ?>">
                    <label class="label"
                           for="<?= $field->getData('key'); ?>"><span><?= $field->getData('label'); ?></span></label>
                    <div class="control">
                        <?php if (in_array($field->getData('field_type'), ['text', 'email'])): ?>
                            <input name="<?= $field->getData('key'); ?>"
                                   id="<?= $field->getData('key'); ?>"
                                   title="<?= $field->getData('label'); ?>"
                                   value="<?= $block->escapeHtml($field->getData('default_value')); ?>"
                                   class="<?= $field->getData('field_class'); ?>"
                                   type="<?= $field->getData('field_type'); ?>">
                        <?php elseif ($field->getData('field_type') == 'textarea'): ?>
                            <textarea name="<?= $field->getData('key'); ?>"
                                      id="<?= $field->getData('key'); ?>"
                                      title="<?= $field->getData('label'); ?>"
                                      class="<?= $field->getData('field_class'); ?>"
                                      style="resize:none"><?= $block->escapeHtml($field->getData('default_value')); ?></textarea>
                        <?php elseif ($field->getData('field_type') == 'checkbox'): ?>
                            <input type="checkbox" name="<?= $field->getData('key'); ?>"
                                   id="<?= $field->getData('key'); ?>"
                                   title="<?= $field->getData('label'); ?>"
                                   value="<?= $block->escapeHtml($field->getData('default_value')); ?>"
                                   class="<?= $field->getData('field_class'); ?>"
                                   type="<?= $field->getData('field_type'); ?>">
                            <label for="<?= $field->getData('key'); ?>">
                                <?= $block->escapeHtml($field->getData('default_value')); ?>
                            </label>
                        <?php elseif ($field->getData('field_type') == 'select'): ?>
                            <select name="<?= $field->getData('key'); ?>" id="<?= $field->getData('key'); ?>">
                                <?php foreach(explode('|', $field->getData('options')) as $value): ?>
                                    <option value="<?= $block->escapeHtml($value); ?>"
                                        <?php if ($field->getData('default_value') == $value) echo " selected" ?>
                                    >
                                        <?= $block->escapeHtml($value); ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        <?php elseif ($field->getData('field_type') == 'checkbox_list'): ?>
                            <?php foreach (explode('|', $field->getData('options')) as $index => $value): ?>
                                <p>
                                    <input type="checkbox" name="<?= $field->getData('key'); ?>[]"
                                           id="<?= $field->getData('key') . $index; ?>"
                                           title="<?= $field->getData('label'); ?>"
                                           value="<?= $block->escapeHtml($value); ?>"
                                           class="<?= $field->getData('field_class'); ?>"
                                           type="<?= $field->getData('field_type'); ?>"
                                        <?php if ($field->getData('default_value') == $value) {
                                            echo " selected";
                                        } ?>
                                    >
                                    <label for="<?= $field->getData('key') . $index; ?>">
                                        <?= $block->escapeHtml($value); ?>
                                    </label>
                                </p>
                            <?php endforeach ?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="">
                <button type="submit" title="<?= __('Submit'); ?>" class="action submit primary">
                    <span><?= __('Submit'); ?></span>
                </button>
            </div>
        </div>
    </form>
<?php endif; ?>
